use_frameworks!

target 'YXYBaseViewController_Example' do
  pod 'YXYBaseViewController', :path => '../'

#  target 'YXYBaseViewController_Tests' do
#    inherit! :search_paths
#
#    pod 'Specta'
#    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
#    pod 'Expecta+Snapshots'
#  end
end
